## 테스트
GET http://localhost:3000 HTTP/1.1

### 전체 유저 목록 가져오기
GET http://localhost:3000/users HTTP/1.1


### 특정 유저 데이터 불러오기
GET http://localhost:3000/user/1 HTTP/1.1

### 유저 추가하기
POST http://localhost:3000/user HTTP/1.1
// body를 인식시키기 위해서 body의 Content Type를 명시해줘야 한다.
Content-Type: application/json

{
    "id":1,
    "twtId":"@twitter1",
    "name":"트위터유저1"
}

### 유저 추가하기 2
POST http://localhost:3000/user HTTP/1.1
// body를 인식시키기 위해서 body의 Content Type를 명시해줘야 한다.
Content-Type: application/json

{
    "id":2,
    "twtId":"@twitter2",
    "name":"트위터유저2"
}

### 특정 유저 업데이트
PATCH http://localhost:3000/user/1 HTTP/1.1
Content-Type: application/json

{
    "twtId":"@twitter_",
    "name":"파랑새"
}